# This file (and others in `conf/`) specify some static parameters,
# as well as some which will be 'swept' over for experiments.

defaults:
    - _self_
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog

# ===== Common parameters for all benchmarks =====
s3_bucket: ???
<<<<<<< HEAD
=======
s3_prefix: !!null

read_part_size: !!null
write_part_size: 16777216 # to allow for uploads of 100GiB

metadata_ttl: "indefinite"

fio_benchmarks:
  - sequential_read

# Path to Mountpoint binary. Recommended to use an absolute path.
mountpoint_binary: !!null
mountpoint_debug: false
mountpoint_debug_crt: false

# No configuration out of the box, use defaults.
network:
  interface_names: []
  maximum_throughput_gbps: !!null

# For overriding upload checksums configured for Mountpoint. Passed as `--upload-checksums` argument.
upload_checksums: !!null

# For overriding fuse max_background and congestion threshold setttings
# environment variables
mountpoint_max_background: !!null
mountpoint_congestion_threshold: !!null

# For monitoring network bandwidth
with_bwm: false

# Works automatically ONLY where this script manages compilation. It has no effect if `mountpoint_binary` is set.
stub_mode: "fs_handler" # fs_handler
mountpoint_clone_fuse_fd: false
iterations: 1

# Define defaults for these columns, but script will run as MULTIRUN by default
fuse_threads: !!null
>>>>>>> e4432a94 (Put the FUSE_DEV_IOC_CLONE behind env var)
application_workers: 1
iteration: 0
iterations: 1
run_time: 30 # Default run time in seconds
read_size: 262144 # Defaults to 256KiB, can go up to 1MiB.
read_part_size: !!null
region: "us-east-1"
write_part_size: 16777216 # 16 MiB, to allow for uploads of large files
object_size_in_gib: 100 # Size of the object to benchmark
benchmark_type: "fio" # fio, prefetch, client, client-bp, crt
s3_keys: !!null # Network configuration


network:
    interface_names: []
    maximum_throughput_gbps:
        !!null # Monitoring options (common to all benchmarks)


monitoring:
    with_bwm: false
    with_perf_stat: false

# ===== Mountpoint configuration =====
mountpoint:
    fuse_threads: !!null
    prefix: !!null
    metadata_ttl: "indefinite"
    mountpoint_max_background: !!null
    mountpoint_congestion_threshold: !!null
    mountpoint_binary: !!null
    upload_checksums: !!null
    stub_mode: "off" # Options: "off", "fs_handler", "s3_client"
    mountpoint_debug: false
    mountpoint_debug_crt: false
    mountpoint_clone_fuse_fd: true

# ===== Benchmark-specific configurations =====
benchmarks:
    fio:
        direct_io: false
        fio_benchmarks:
            - sequential_read
        fio_benchmark: "${benchmarks.fio.fio_benchmarks[0]}"
        fio_io_engine: "psync"

    prefetch:
        max_memory_target: !!null

    crt:
        crt_benchmarks_path: !!null

    client:
        # None

    client_backpressure:
        read_window_size: !!null #2147483648


hydra:
<<<<<<< HEAD
    help:
        app_name: "Mountpoint benchmark runner"
    mode: MULTIRUN
    job:
        chdir: true
    sweeper:
        # Global sweeper params - use this for common parameters across all benchmarks
        # For specific parameter use sweep params under the specific benchmark type config
        params:
            "application_workers": 1, 4, 16, 64, 128
            "mountpoint_clone_fuse_fd": false, true
            "iteration": "range(${iterations})"
            "mountpoint.fuse_threads": 1, 16, 64
            "benchmarks.fio.direct_io": false, true
            # 'benchmarks.prefetch.max_memory_target': !!null, 1073741824, 2147483648  # null, 1GB, 2GB
            #'benchmarks.client_backpressure.read_window_size': 8388608, 2147483648
=======
  help:
    app_name: "Mountpoint sequential read experiment runner"
  mode: MULTIRUN
  job:
    chdir: true
  sweeper:
    params:
      # Maximum number of FUSE threads for Mountpoint. Passed as `--max-threads` argument.
      'fuse_threads': 1, 3, 16
      # Number of processes that will be interacting with the file.
      'application_workers': 1, 16
      # Configure if application should use Direct IO, skipping the Linux page cache
      'direct_io': true
      'mountpoint_clone_fuse_fd': false, true
      # Don't touch the params below, they are based on settings above.
      'fio_benchmark': "${join:',', ${fio_benchmarks}}"
      'iteration': "range(${iterations})"
>>>>>>> e4432a94 (Put the FUSE_DEV_IOC_CLONE behind env var)
